docker: Initial Dockerfile
CESARBR/zephyr-knot-sdk pull request #31
Opened 2019-06-17 19:24 UTC by jcorde

Create Dockerfile derived from the original Dockerfile for Zephyr
Project's Docker image.

Changes:
	Remove VNC support.
 	Cloning Zephyr and KNoT used git repositories.
	Always using CESAR's Zephyr Project git fork.
	Install Zephyr-KNoT-SDK requirements.
	Allow user to use desired folder as current working directory.
	Install Segger Jlink drivers from an external file.

The Segger Jlink drivers path has to be provided during compilation.

Add LICENSE.txt file as the original project is protected by Apache
License.

Closes: #27

Signed-off-by: jvccCESAR <jvcc@cesar.org.br>

2019-06-18 12:57 UTC, ramonhpr reviewed
The patch is good. Just add a README on how to build and run it.

2019-06-18 19:59 UTC, vitbaq reviewed
I agree with Ramon

2019-06-26 11:05 UTC, jcorde commented
Hi, @vitbaq and @ramonhpr . I just added the README file to https://github.com/CESARBR/zephyr-knot-sdk/pull/31/commits/31a484648584495d35ff0d3d71265ab54bc5e204

2019-06-27 14:02 UTC, vitbaq requested changes
Makes it clear that inside docker the user can use cli functions and link with cli guide.
And illustrate when the user is in the docker container terminal.

2019-06-27 17:56 UTC, jcorde commented
@vitbaq changes made to README file

2019-06-28 12:07 UTC, vitbaq approved these changes

2019-06-28 18:50 UTC, merged