boards: Add support to KNoT Mesh
CESARBR/zephyr-knot-sdk pull request #57
Opened 2019-09-18 14:22 UTC by jcorde

Add support to knot_mesh board based on Dongle.

Using the same mcuboot image as nrf52840_pca10059.
This has to be fixed so the push button 0 will be assigned to the
correct pin.

It assumes that a similar DFU bootloader from Dongle's is used.
Although the same bootloader is not suggested as the LED 0 is assigned
to a different pin.

Depends on https://github.com/CESARBR/zephyr/pull/4 .

Signed-off-by: Joao Cordeiro <jvcc@cesar.org.br>

2019-09-18 19:37 UTC, jcorde commented
The flash areas have to be fixed for KNoT Mesh and Debug for Dongle

2019-09-19 18:09 UTC, ramonhpr requested changes

2019-09-19 18:09 UTC, ramonhpr commented on core/boards/knot_mesh-sub-slots-stock.dts
> +			reg = <0x00030000 0x00003E000>;
0x00003**e**000

2019-09-19 19:36 UTC, jcorde commented on core/boards/knot_mesh-sub-slots-stock.dts
> +			reg = <0x00030000 0x00003E000>;
Done

2019-09-19 21:20 UTC, alla3 approved these changes

2019-09-20 12:12 UTC, merged